import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

test("production shell exists", () => {
  assert.equal(fs.existsSync("app/page.tsx"), true);
  assert.equal(fs.existsSync("app/AuthApp.tsx"), true);
  assert.equal(fs.existsSync("next.config.mjs"), true);
  assert.equal(fs.existsSync("public/manifest.webmanifest"), true);
  assert.equal(fs.existsSync("public/sw.js"), true);
  assert.equal(fs.existsSync("public/offline.html"), true);
  const page = fs.readFileSync("app/page.tsx", "utf8");
  const auth = fs.readFileSync("app/AuthApp.tsx", "utf8");
  const layout = fs.readFileSync("app/layout.tsx", "utf8");
  const styles = fs.readFileSync("app/globals.css", "utf8");
  const manifest = fs.readFileSync("public/manifest.webmanifest", "utf8");
  const serviceWorker = fs.readFileSync("public/sw.js", "utf8");
  const nextConfig = fs.readFileSync("next.config.mjs", "utf8");
  assert.match(page, /AuthApp/);
  assert.match(auth, /GreenBusiness/);
  assert.match(auth, /\/api\/v1\/auth\/refresh/);
  assert.match(auth, /\/api\/v1\/auth\/dev\/creator/);
  assert.match(auth, /Entrar como creador/);
  assert.match(auth, /\/api\/health\/live/);
  assert.match(auth, /\/api\/v1\/production\/slots/);
  assert.match(auth, /\/api\/v1\/economy\/offers/);
  assert.match(auth, /\/api\/v1\/economy\/contracts/);
  assert.match(auth, /\/api\/v1\/economy\/upgrades/);
  assert.match(auth, /\/api\/v1\/social\/me/);
  assert.match(auth, /\/api\/v1\/clubs/);
  assert.match(auth, /\/api\/v1\/store\/catalog/);
  assert.match(auth, /\/api\/v1\/store\/purchases\/validate/);
  assert.match(auth, /\/api\/v1\/notifications\/me/);
  assert.match(auth, /\/api\/v1\/notifications\/preferences/);
  assert.match(auth, /serviceWorker\.register/);
  assert.match(auth, /window\.confirm/);
  assert.match(auth, /absoluteTimestamp/);
  assert.match(auth, /Ready at/);
  assert.match(auth, /aria-pressed/);
  assert.match(auth, /Convenience, never coercion/);
  assert.match(auth, /Clubhouse/);
  assert.match(auth, /Ethical monetization sandbox/);
  assert.match(auth, /Friend code/);
  assert.match(auth, /premium_credits/);
  assert.match(auth, /active_entitlement_keys/);
  assert.match(auth, /Cash/);
  assert.match(auth, /contract_refresh_at/);
  assert.match(auth, /active_contracts/);
  assert.match(auth, /skill_points_unspent/);
  assert.match(auth, /contacts/);
  assert.match(auth, /missions/);
  assert.match(auth, /daily_mission_keys/);
  assert.match(auth, /weekly_mission_keys/);
  assert.match(auth, /mastery/);
  assert.match(auth, /Missions & mastery/);
  assert.match(auth, /server_time/);
  assert.match(auth, /serverClockOffsetMs/);
  assert.match(auth, /Starter varieties/);
  assert.match(auth, /StarterRoomScene/);
  assert.equal(fs.existsSync("app/StarterRoomScene.tsx"), true);
  assert.equal(fs.existsSync("app/gameAssets.ts"), true);
  assert.match(auth, /API offline/);
  assert.match(auth, /credentials: "include"/);
  assert.match(layout, /manifest\.webmanifest/);
  assert.match(layout, /appleWebApp/);
  assert.match(styles, /focus-visible/);
  assert.match(styles, /prefers-reduced-motion/);
  assert.match(styles, /toggle-card\.enabled/);
  assert.match(manifest, /GreenBusiness/);
  assert.match(manifest, /standalone/);
  assert.match(serviceWorker, /offline\.html/);
  assert.match(serviceWorker, /pathname\.startsWith\("\/api\/"\)/);
  assert.match(nextConfig, /API_INTERNAL_URL/);
  assert.match(nextConfig, /source: "\/api\/:path\*"/);
});
