import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

test("production shell exists", () => {
  assert.equal(fs.existsSync("app/page.tsx"), true);
  assert.equal(fs.existsSync("app/AuthApp.tsx"), true);
  assert.equal(fs.existsSync("next.config.mjs"), true);
  const page = fs.readFileSync("app/page.tsx", "utf8");
  const auth = fs.readFileSync("app/AuthApp.tsx", "utf8");
  const nextConfig = fs.readFileSync("next.config.mjs", "utf8");
  assert.match(page, /AuthApp/);
  assert.match(auth, /GreenBusiness/);
  assert.match(auth, /\/api\/v1\/auth\/refresh/);
  assert.match(auth, /\/api\/health\/live/);
  assert.match(auth, /\/api\/v1\/production\/slots/);
  assert.match(auth, /\/api\/v1\/economy\/offers/);
  assert.match(auth, /\/api\/v1\/economy\/contracts/);
  assert.match(auth, /\/api\/v1\/economy\/upgrades/);
  assert.match(auth, /Cash/);
  assert.match(auth, /contract_refresh_at/);
  assert.match(auth, /active_contracts/);
  assert.match(auth, /skill_points_unspent/);
  assert.match(auth, /contacts/);
  assert.match(auth, /missions/);
  assert.match(auth, /daily_mission_keys/);
  assert.match(auth, /weekly_mission_keys/);
  assert.match(auth, /mastery/);
  assert.match(auth, /Missions & mastery/);
  assert.match(auth, /server_time/);
  assert.match(auth, /serverClockOffsetMs/);
  assert.match(auth, /Starter varieties/);
  assert.match(auth, /room-scene/);
  assert.match(auth, /API offline/);
  assert.match(auth, /credentials: "include"/);
  assert.match(nextConfig, /API_INTERNAL_URL/);
  assert.match(nextConfig, /source: "\/api\/:path\*"/);
});

test("liveops admin API surfaces are wired", () => {
  const api = fs.readFileSync("../api/app/api.py", "utf8");
  const adminRoutes = fs.readFileSync("../api/app/admin_routes.py", "utf8");
  assert.match(api, /admin_router/);
  assert.match(api, /liveops_router/);
  assert.match(adminRoutes, /\/experiments/);
  assert.match(adminRoutes, /\/config\/publish/);
  assert.match(adminRoutes, /\/config\/rollback/);
  assert.match(adminRoutes, /\/config\/versions/);
  assert.match(adminRoutes, /\/ledger/);
  assert.match(adminRoutes, /\/cash\/grant/);
  assert.match(adminRoutes, /\/cash\/revoke/);
  assert.match(adminRoutes, /\/dashboards\/economy/);
  assert.match(adminRoutes, /\/dashboards\/core-funnel/);
  assert.match(adminRoutes, /\/dashboards\/core-loop/);
});
