import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

test("production shell exists", () => {
  assert.equal(fs.existsSync("app/page.tsx"), true);
  assert.equal(fs.existsSync("app/AuthApp.tsx"), true);
  assert.equal(fs.existsSync("next.config.mjs"), true);
  const page = fs.readFileSync("app/page.tsx", "utf8");
  const auth = fs.readFileSync("app/AuthApp.tsx", "utf8");
  const nextConfig = fs.readFileSync("next.config.mjs", "utf8");
  assert.match(page, /AuthApp/);
  assert.match(auth, /GreenBusiness/);
  assert.match(auth, /\/api\/v1\/auth\/refresh/);
  assert.match(auth, /\/api\/health\/live/);
  assert.match(auth, /\/api\/v1\/production\/slots/);
  assert.match(auth, /\/api\/v1\/contracts/);
  assert.match(auth, /\/api\/v1\/contracts\/reroll/);
  assert.match(auth, /server_time/);
  assert.match(auth, /serverClockOffsetMs/);
  assert.match(auth, /Starter varieties/);
  assert.match(auth, /Contracts/);
  assert.match(auth, /cash_balance/);
  assert.match(auth, /reputation_reward/);
  assert.match(auth, /contract_board/);
  assert.match(auth, /Reroll/);
  assert.match(auth, /progression/);
  assert.match(auth, /skill_points/);
  assert.match(auth, /\/api\/v1\/skills/);
  assert.match(auth, /cash_ledger/);
  assert.match(auth, /economy_summary/);
  assert.match(auth, /\/api\/v1\/upgrades/);
  assert.match(auth, /Upgrades/);
  assert.match(auth, /Progression/);
  assert.match(auth, /Skills/);
  assert.match(auth, /Respec/);
  assert.match(auth, /Economy summary/);
  assert.match(auth, /Cash ledger/);
  assert.match(auth, /room-scene/);
  assert.match(auth, /API offline/);
  assert.match(auth, /credentials: "include"/);
  assert.match(nextConfig, /API_INTERNAL_URL/);
  assert.match(nextConfig, /source: "\/api\/:path\*"/);
});
